@bot.command()
async def code(ctx):
    embed=discord.Embed(title="指令大全", description="", color=0x2160f2)
    embed.set_thumbnail(url="https://cdn.icon-icons.com/icons2/936/PNG/512/code_icon-icons.com_73620.png")
    embed.add_field(name=";about", value="可以查看關於我的訊息", inline=False)
    embed.add_field(name=";code", value="可以查看指令大全", inline=False)
    embed.add_field(name=";ping", value="可以查看毫秒", inline=False)
    embed.add_field(name=";game", value="可以查看虎鯨有玩的遊戲", inline=False)
    embed.add_field(name=";join/leave", value="可以讓機器咩咩加入/退出你所在的語音頻道", inline=False)
    embed.add_field(name=";sayd 你要說的話", value="可以讓機器咩咩說話(僅限虎鯨咩咩使用)", inline=False)
    embed.add_field(name=";clean 幾行", value="可以刪除上面幾行訊息(僅限虎鯨咩咩使用)", inline=False)
    embed.add_field(name=";vote 投票主題", value="可以開啟投票(僅限虎鯨咩咩使用)", inline=False)
    embed.add_field(name=";giverole @自己", value="如果沒拿到觀眾身分組請用這個指令", inline=False)
    embed.add_field(name=";generate 想要的主題", value="可以生成圖畫(Ai畫家)", inline=False)
    embed.add_field(name=";weather 你想查詢的城市(要用英文)", value="可以查看天氣", inline=False)
    embed.set_footer(text="指令未來將持續更新")
    await ctx.send(embed=embed)