@bot.command()
async def about(ctx):
    embed = discord.Embed(title="關於機器咩咩",url="https://www.youtube.com/@orcasheep/featured",description="生產日期2023/03/04",color=0x2160f2)
    embed.set_author(name="作者:dragon")
    embed.set_thumbnail(url="https://yt3.googleusercontent.com/vS1pFquZ8l0UNUwdUg-fxI4AUoznqnibjS62tJcO1WZKc9Ps2vEfm6cF9vL0p9b0-EDQjmx2_w=s176-c-k-c0x00ffffff-no-rj")
    embed.add_field(name="版本", value="正式版1.0.0.9", inline=False)
    embed.add_field(name="使用語言", value="python", inline=False)
    embed.add_field(name="指令開頭", value=";", inline=False)
    embed.add_field(name="款式", value="虎鯨款", inline=False)
    embed.set_footer(text="本產品授權給虎鯨咩咩")
    await ctx.send(embed=embed)